/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DatabaseController;
import Model.Case;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian
 */
public class InsertCases extends javax.swing.JFrame {
DatabaseController dbc = new DatabaseController();

    /**
     * Creates new form InsertCases
     */
    public InsertCases() throws SQLException {
        initComponents();
        fillCaselistComboBox();
    }
    public Connection getConnection() {
        Connection conn = null;
        try {
           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javauppgift?zeroDateTimeBehavior=convertToNull&useSSL=false","root","hejsan");
            System.out.println("Connectad till databasen");
            return conn;
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return null;
        }
        
    }
    
    public void fillCaselistComboBox() {
        
        try {
            dbc.connectToDB();
            Statement st = (Statement) getConnection().createStatement();
            ResultSet rs = st.executeQuery("Select caseCategoryName from casecategorytbl");
            while(rs.next()){
                comboboxArbetsuppgift.addItem(rs.getString(1));
            }
           
       
        } catch (SQLException e) {
            e.getMessage();
        }
        
    }
    
    public ArrayList getCaseList(){
        ArrayList<Case> caseList = new ArrayList<>();
        for(Case c : caseList){
            c.getBudgetTime();
            c.getStatus();
        }
        return caseList;
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboboxArbetsuppgift = new javax.swing.JComboBox<>();
        labelArbetsuppgift = new javax.swing.JLabel();
        txt_budget = new javax.swing.JTextField();
        label_budgetTIme = new javax.swing.JLabel();
        button_done = new javax.swing.JButton();
        button_plus = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        comboboxArbetsuppgift.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        comboboxArbetsuppgift.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxArbetsuppgiftActionPerformed(evt);
            }
        });

        labelArbetsuppgift.setText("Arbetsuppgift:");

        txt_budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_budgetActionPerformed(evt);
            }
        });

        label_budgetTIme.setText("Budgeterad tid (timmar)");

        button_done.setText("Klar");
        button_done.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_doneActionPerformed(evt);
            }
        });

        button_plus.setText("+");
        button_plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_plusActionPerformed(evt);
            }
        });

        button_cancel.setText("Avbryt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboboxArbetsuppgift, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelArbetsuppgift))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_budgetTIme)
                    .addComponent(txt_budget, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(button_cancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_plus)
                    .addComponent(button_done))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelArbetsuppgift)
                    .addComponent(label_budgetTIme))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxArbetsuppgift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_budget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_plus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_done)
                    .addComponent(button_cancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_budgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_budgetActionPerformed

    private void comboboxArbetsuppgiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxArbetsuppgiftActionPerformed
       
    }//GEN-LAST:event_comboboxArbetsuppgiftActionPerformed

    private void button_doneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_doneActionPerformed
    try {
        
        dbc.addCase(comboboxArbetsuppgift.getSelectedIndex(), txt_budget.getText());
    } catch (SQLException ex) {
        Logger.getLogger(InsertCases.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_button_doneActionPerformed

    private void button_plusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_plusActionPerformed
        ArrayList<Case> caseList = new ArrayList<>();
        int budget = Integer.parseInt(txt_budget.getText().toString());
        int caseCategory = comboboxArbetsuppgift.getSelectedIndex();
        Case c = new Case(budget,caseCategory);
        caseList.add(c);
       
   
    
    }//GEN-LAST:event_button_plusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertCases().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(InsertCases.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_done;
    private javax.swing.JButton button_plus;
    private javax.swing.JComboBox<String> comboboxArbetsuppgift;
    private javax.swing.JLabel labelArbetsuppgift;
    private javax.swing.JLabel label_budgetTIme;
    private javax.swing.JTextField txt_budget;
    // End of variables declaration//GEN-END:variables
}
