/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CaseController;
import Controller.DatabaseController;
import Controller.TaskController;
import Observer.TaskObserver;

import java.sql.Connection;
import java.sql.DriverManager;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author sebastian
 */
public class TaskExecutor extends javax.swing.JFrame implements TaskObserver{
    TaskController tc;
    TableModel model;
    DatabaseController dbc;
    
    String url = "jdbc:mysql://localhost:3306/javauppgift?zeroDateTimeBehavior=convertToNull&useSSL=false";
    String user = "root";
    String password = "hejsan";
         
    /**
     * Creates new form ViewMyTasks
     */
    public TaskExecutor() {
        initComponents();
        try {
            tc = new TaskController();
            tc.addListener(this);
        } catch (SQLException ex) {
            System.out.println("Kunde inte connecta till databasen"+ex.getMessage());
        }
        initShowTaskTable();
        initShowCaseTable();
        
        
       
        this.dbc = new DatabaseController();
    }
    
    
    
    public void initShowTaskTable(){
        ArrayList<Model.Task> taskList = new ArrayList<>();
        try {
            
            taskList = tc.getAllTasks();
            int row = 0;
            int rows = taskList.size();
            
            Object[][] data = new Object[rows][4];
            
            for(Model.Task t : taskList){
              data[row][0] = t.getTaskID();
              data[row][1] = t.getCategory();
              data[row][2] = t.getDescription();
              data[row][3] = t.getTaskManagerName();
              row++;
            }
            model = new DefaultTableModel(data, Constants.MyTask_TABLE_HEADER);
            tbl_tasks.setModel(model);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Misslyckades att visa ärendetabellen");
            System.out.println(ex.getMessage());
        }
    }
    
    public void initShowCaseTable(){
        ArrayList<Model.Case> caseList = new ArrayList<>();
        try {
            CaseController dc = new CaseController();
            caseList = dc.getAllDutys();
            int row = 0;
            int rows = caseList.size();
            
            Object[][] data = new Object[rows][7];
            
            for(Model.Case d : caseList){
              data[row][0] = d.getTaskID();
              data[row][1] = d.getDutyCase();
              data[row][2] = d.getBudgetTime();
              data[row][3] = d.getTimePerformed();
              data[row][4] = d.getCaseEmployeeID();
              data[row][5] = d.getComment();
              data[row][6] = d.getStatus();
              
              row++;
            }
            model = new DefaultTableModel(data, Constants.MyTaskDuty_TABLE_HEADER);
            tbl_Cases.setModel(model);
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Kunde inte hämta data från arbetsuppgifter");
            System.out.println(ex.getMessage());
            
        }
    }
    
    public Connection getConnection(){
        try {
            Connection conn = DriverManager.getConnection(url,user,password);
            return conn;
        } catch (SQLException ex) {
            System.out.println("Connectad till databasen "+ex.getMessage());
            return null;
        }
        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Cases = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_tasks = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        button_Task_update = new javax.swing.JButton();
        button_Task_delete = new javax.swing.JButton();
        button_Case_attest = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        button_INSERT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 500));

        tbl_Cases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbl_Cases);

        tbl_tasks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_tasks.getTableHeader().setReorderingAllowed(false);
        tbl_tasks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_tasksMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_tasks);

        jLabel1.setText("Ärenden:");

        jLabel2.setText("Arbetsuppgifter:");

        button_Task_update.setText("Ändra");
        button_Task_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Task_updateActionPerformed(evt);
            }
        });

        button_Task_delete.setText("Ta bort");
        button_Task_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Task_deleteActionPerformed(evt);
            }
        });

        button_Case_attest.setText("Attestera");
        button_Case_attest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_Case_attestActionPerformed(evt);
            }
        });

        button_cancel.setText("Tillbaka");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_INSERT.setText("Skapa");
        button_INSERT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_INSERTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_INSERT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Task_update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_Task_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(139, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(button_Case_attest)))
                            .addGap(140, 140, 140))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(43, 43, 43)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(242, 242, 242))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(button_INSERT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Task_update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Task_delete))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Case_attest)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        ViewMain vm = new ViewMain();
        vm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_button_cancelActionPerformed

    private void button_INSERTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_INSERTActionPerformed
        try {
            CreateNewTask cnt = new CreateNewTask();
            cnt.setVisible(true);
           
        } catch (SQLException ex) {
            Logger.getLogger(TaskExecutor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button_INSERTActionPerformed

    private void button_Task_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Task_updateActionPerformed
    try{
      int row = tbl_tasks.getSelectedRow();
      int id = Integer.parseInt(tbl_tasks.getValueAt(row, 0).toString());
      String newDescription = JOptionPane.showInputDialog("Skriv in en ny beskrivning").toString();
     int status = dbc.updateTask(newDescription, id);
      //Skriv statement och rs här.
    }catch(SQLException ex){
        System.out.println("gick inte att uppdatera"+ex.getMessage());
    }
    }//GEN-LAST:event_button_Task_updateActionPerformed

    private void tbl_tasksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_tasksMouseClicked
      

    }//GEN-LAST:event_tbl_tasksMouseClicked

    private void button_Task_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Task_deleteActionPerformed
      
      int row = tbl_tasks.getSelectedRow();
      int id = Integer.parseInt(tbl_tasks.getValueAt(row, 0).toString());
        try {
            int dialogBox = JOptionPane.showConfirmDialog(this, "Vill du verkligen ta bort ärendenr: +"
                    +id+"?", "Radera ärende", JOptionPane.YES_NO_OPTION);
            if(dialogBox == JOptionPane.YES_OPTION){
            dbc.deleteTask(id);
            }else{
                this.setVisible(true);
            }
        } catch (SQLException ex) {
            System.out.println("Gick inte att radera valt ärende" +ex.getMessage());
        }
    
  
    }//GEN-LAST:event_button_Task_deleteActionPerformed

    private void button_Case_attestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_Case_attestActionPerformed
       int row = tbl_Cases.getSelectedRow();
       
      int id = Integer.parseInt(tbl_Cases.getValueAt(row, 0).toString());
      String statusrow = tbl_Cases.getValueAt(row,6 ).toString();
    
        try {
            int status = dbc.updateCase(id);
            //Skriv statement och rs här.
        } catch (SQLException ex) {
            System.out.println("Det gick inte uppdatera arbetsuppgiften "+ex.getMessage() );
        }
    

    
    
    
    }//GEN-LAST:event_button_Case_attestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskExecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskExecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskExecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskExecutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskExecutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Case_attest;
    private javax.swing.JButton button_INSERT;
    private javax.swing.JButton button_Task_delete;
    private javax.swing.JButton button_Task_update;
    private javax.swing.JButton button_cancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_Cases;
    private javax.swing.JTable tbl_tasks;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
        initShowTaskTable();
        initShowCaseTable();
    }

    

    
    
}
