/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DatabaseController;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author sebastian
 */
public class ViewNewTask extends javax.swing.JFrame {
DatabaseController dbc;
    /**
     * Creates new form ViewJframe
     */
    public ViewNewTask() throws SQLException {
        this.dbc = new DatabaseController();
        initComponents();
        fillCategoryComboBox();
        fillTaskManagerComboBox();
        fillCaseComboBox();
    }

    //Öppna upp en connection till databasen
    public Connection getConnection() {
        Connection conn = null;
        try {
           conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/javauppgift?zeroDateTimeBehavior=convertToNull&useSSL=false","root","hejsan");
            System.out.println("Connectad till databasen");
            return conn;
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            return null;
        }
        
    }
    //Fyll comboboxen för taskmasters med namn
    public void fillTaskManagerComboBox() throws SQLException{
        dbc.connectToDB();
        
            Statement st = (Statement) getConnection().createStatement();
            ResultSet rs = st.executeQuery("Select taskManagerName from taskmanagertbl");
            while(rs.next()){
                ComboBox_TaskManager.addItem(rs.getString("taskManagerName"));
            }
            dbc.closeConnectionToDB();
       
    }
    
    //Fyll comboboxen med olika kategorier
    public void fillCategoryComboBox(){
        getConnection();
        try {
            Statement st = (Statement) getConnection().createStatement();
            ResultSet rs = st.executeQuery("Select taskcategoryName from taskcategorytbl");
            while(rs.next()){
                ComboBox_Category.addItem(rs.getString("taskcategoryName"));
            }
            getConnection().close();
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }
    
    //fyll comboboxen med arbetsuppgifter
    public void fillCaseComboBox(){
        getConnection();
        try {
            Statement st = (Statement) getConnection().createStatement();
            ResultSet rs = st.executeQuery("Select caseCategoryName from casecategorytbl");
            while(rs.next()){
                ComboBox_case.addItem(rs.getString("caseCategoryName"));
            }
            getConnection().close();
        } catch (SQLException ex) {
            ex.getMessage();
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button_cancel = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ComboBox_Category = new javax.swing.JComboBox<>();
        Label_Category = new javax.swing.JLabel();
        Label_Description = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Description = new javax.swing.JTextArea();
        Label_CreatedBy = new javax.swing.JLabel();
        ComboBox_TaskManager = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        ComboBox_case = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txt_budget = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Fiktivt AB Ärendehanteringssystem");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        button_cancel.setText("Avbryt");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });

        button_save.setText("Spara");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        ComboBox_Category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj kategori..." }));
        ComboBox_Category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_CategoryActionPerformed(evt);
            }
        });

        Label_Category.setText("Kategori: ");

        Label_Description.setText("Beskrivning:");

        TextArea_Description.setColumns(20);
        TextArea_Description.setRows(5);
        jScrollPane1.setViewportView(TextArea_Description);

        Label_CreatedBy.setText("Skapas av:");

        ComboBox_TaskManager.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "välj processledare.." }));
        ComboBox_TaskManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_TaskManagerActionPerformed(evt);
            }
        });

        jLabel3.setText("Arbetsuppgift:");

        ComboBox_case.setMaximumRowCount(15);
        ComboBox_case.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        ComboBox_case.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_caseActionPerformed(evt);
            }
        });

        jLabel4.setText("Budgeterad tid");

        txt_budget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_budgetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBox_case, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(Label_CreatedBy)
                    .addComponent(Label_Category)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(ComboBox_TaskManager, javax.swing.GroupLayout.Alignment.LEADING, 0, 124, Short.MAX_VALUE)
                        .addComponent(ComboBox_Category, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txt_budget, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(330, 330, 330)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(Label_Description))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(Label_CreatedBy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ComboBox_TaskManager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(Label_Category)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ComboBox_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Description))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ComboBox_case, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_budget, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(button_save, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
       ViewMain viewMain = new ViewMain();
       
       viewMain.setVisible(true);
       this.setVisible(false);
       
      
    }//GEN-LAST:event_button_cancelActionPerformed

    private void ComboBox_CategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_CategoryActionPerformed

      
        
    }//GEN-LAST:event_ComboBox_CategoryActionPerformed

    private void ComboBox_caseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_caseActionPerformed
      
    }//GEN-LAST:event_ComboBox_caseActionPerformed

    private void txt_budgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_budgetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_budgetActionPerformed

    private void ComboBox_TaskManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_TaskManagerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox_TaskManagerActionPerformed

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        
            try {
                //Exekvera metoden som lägger till ett meddelande i db
           
                int status = dbc.addTask(ComboBox_Category.getSelectedIndex(), ComboBox_TaskManager.getSelectedIndex(), TextArea_Description.getText());
                
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Det gick inte att lägga till ett nytt ärende");
                System.out.println(ex.getMessage());
            }
            try {
                String info = "pågående";
            int status2 = dbc.addCase(ComboBox_case.getSelectedIndex(),txt_budget.getText(),info );
            JOptionPane.showMessageDialog(null, "Ett nytt ärende med medföljande arbetsuppgifter har skapats!");
            ViewMain vm = new ViewMain();
            vm.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Fel uppstod när ett ny arbetsuppgiftskulleskapas");
                System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_button_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNewTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ViewNewTask().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewNewTask.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Category;
    private javax.swing.JComboBox<String> ComboBox_TaskManager;
    private javax.swing.JComboBox<String> ComboBox_case;
    private javax.swing.JLabel Label_Category;
    private javax.swing.JLabel Label_CreatedBy;
    private javax.swing.JLabel Label_Description;
    private javax.swing.JTextArea TextArea_Description;
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_budget;
    // End of variables declaration//GEN-END:variables
}
